-- Store one normalized embedding per playable word and calculate only the
-- Judge-to-hand similarities needed by the authoritative Edge Function.
--
-- The catalog deliberately lives outside the public API schema. Browser clients
-- must never be able to download the embeddings or call the scoring/import RPCs.

create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;
grant usage on schema private to service_role;

create extension if not exists vector
with schema extensions;

create table if not exists private.word_catalog (
  id bigint generated by default as identity primary key,
  word text not null unique,
  embedding extensions.vector(300) not null,
  embedding_model text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint word_catalog_normalized_word_check
    check (word = lower(trim(word)) and length(word) > 0),
  constraint word_catalog_embedding_model_check
    check (length(trim(embedding_model)) > 0)
);

drop trigger if exists word_catalog_set_updated_at on private.word_catalog;
create trigger word_catalog_set_updated_at
before update on private.word_catalog
for each row execute function public.set_updated_at();

alter table private.word_catalog enable row level security;

grant select, insert, update on private.word_catalog to service_role;
grant usage, select on sequence private.word_catalog_id_seq to service_role;

create or replace function public.upsert_word_embeddings(
  p_embedding_model text,
  p_words jsonb
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public, private, extensions
as $$
declare
  affected_count integer := 0;
begin
  if trim(coalesce(p_embedding_model, '')) = '' then
    raise exception 'Embedding model is required.';
  end if;

  if jsonb_typeof(coalesce(p_words, '[]'::jsonb)) <> 'array' then
    raise exception 'Words payload must be a JSON array.';
  end if;

  insert into private.word_catalog as catalog (
    word,
    embedding,
    embedding_model,
    active
  )
  select
    lower(trim(word_row.value ->> 'word')),
    (word_row.value -> 'embedding')::text::extensions.vector(300),
    trim(p_embedding_model),
    coalesce((word_row.value ->> 'active')::boolean, true)
  from jsonb_array_elements(coalesce(p_words, '[]'::jsonb)) as word_row(value)
  where trim(coalesce(word_row.value ->> 'word', '')) <> ''
    and jsonb_typeof(word_row.value -> 'embedding') = 'array'
  on conflict (word) do update
  set
    embedding = excluded.embedding,
    embedding_model = excluded.embedding_model,
    active = excluded.active,
    updated_at = now();

  get diagnostics affected_count = row_count;
  return affected_count;
end;
$$;

create or replace function public.get_word_catalog_status()
returns table (
  embedding_model text,
  word_count bigint,
  active_word_count bigint
)
language sql
stable
security definer
set search_path = pg_catalog, public, private
as $$
  select
    catalog.embedding_model,
    count(*) as word_count,
    count(*) filter (where catalog.active) as active_word_count
  from private.word_catalog as catalog
  group by catalog.embedding_model
  order by catalog.embedding_model;
$$;

create or replace function public.score_hand_word_similarities(
  p_room_id uuid,
  p_hand_number integer,
  p_judge_word text
)
returns table (
  player_id integer,
  score double precision
)
language sql
stable
security definer
set search_path = pg_catalog, public, private, extensions
as $$
  select
    hand_word.player_id,
    round(
      (
        (
          1 - (player_embedding.embedding <=> judge_embedding.embedding)
        ) * 100
      )::numeric,
      2
    )::double precision as score
  from public.hand_words as hand_word
  join private.word_catalog as player_embedding
    on player_embedding.word = lower(trim(hand_word.word))
  join private.word_catalog as judge_embedding
    on judge_embedding.word = lower(trim(p_judge_word))
  where hand_word.room_id = p_room_id
    and hand_word.hand_number = p_hand_number
  order by hand_word.player_id;
$$;

revoke all on function public.upsert_word_embeddings(text, jsonb) from public;
revoke all on function public.upsert_word_embeddings(text, jsonb) from anon;
revoke all on function public.upsert_word_embeddings(text, jsonb) from authenticated;
grant execute on function public.upsert_word_embeddings(text, jsonb) to service_role;

revoke all on function public.get_word_catalog_status() from public;
revoke all on function public.get_word_catalog_status() from anon;
revoke all on function public.get_word_catalog_status() from authenticated;
grant execute on function public.get_word_catalog_status() to service_role;

revoke all on function public.score_hand_word_similarities(uuid, integer, text) from public;
revoke all on function public.score_hand_word_similarities(uuid, integer, text) from anon;
revoke all on function public.score_hand_word_similarities(uuid, integer, text) from authenticated;
grant execute on function public.score_hand_word_similarities(uuid, integer, text) to service_role;

comment on table private.word_catalog is
  'Server-only normalized word embeddings used for on-demand multiplayer similarity scoring.';

comment on function public.score_hand_word_similarities(uuid, integer, text) is
  'Service-role-only Judge-to-hand cosine scores. Returns one score per stored hand word.';
