create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  host_user_id uuid not null references auth.users (id) on delete cascade,
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'finished')),
  max_players integer not null default 4 check (max_players between 2 and 8),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.room_players (
  room_id uuid not null references public.rooms (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  display_name text not null check (length(trim(display_name)) between 1 and 32),
  seat_index integer not null check (seat_index >= 0),
  is_ready boolean not null default false,
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id),
  unique (room_id, seat_index)
);

create table if not exists public.room_states (
  room_id uuid primary key references public.rooms (id) on delete cascade,
  version integer not null default 1 check (version > 0),
  state_json jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.room_actions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms (id) on delete cascade,
  actor_user_id uuid not null references auth.users (id) on delete cascade,
  action_type text not null check (length(trim(action_type)) > 0),
  payload jsonb not null default '{}'::jsonb,
  accepted boolean not null default false,
  error_text text,
  version_before integer,
  version_after integer,
  created_at timestamptz not null default now()
);

create index if not exists room_players_room_id_idx on public.room_players (room_id);
create index if not exists room_actions_room_id_idx on public.room_actions (room_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rooms_set_updated_at on public.rooms;
create trigger rooms_set_updated_at
before update on public.rooms
for each row execute function public.set_updated_at();

drop trigger if exists room_states_set_updated_at on public.room_states;
create trigger room_states_set_updated_at
before update on public.room_states
for each row execute function public.set_updated_at();

create or replace function public.generate_room_code()
returns text
language plpgsql
as $$
declare
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code text := '';
  i integer;
begin
  for i in 1..6 loop
    code := code || substr(chars, 1 + floor(random() * length(chars))::int, 1);
  end loop;

  return code;
end;
$$;

create or replace function public.is_room_member(target_room_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.room_players member_row
    where member_row.room_id = target_room_id
      and member_row.user_id = auth.uid()
  );
$$;

create or replace function public.create_room(p_display_name text default 'Player')
returns table (room_id uuid, room_code text, seat_index integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text;
  generated_code text;
  generated_room_id uuid;
  tries integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  clean_name := left(coalesce(nullif(trim(p_display_name), ''), 'Player'), 32);

  loop
    tries := tries + 1;
    generated_code := public.generate_room_code();

    begin
      insert into public.rooms (code, host_user_id, status, max_players)
      values (generated_code, auth.uid(), 'waiting', 4)
      returning id into generated_room_id;
      exit;
    exception when unique_violation then
      if tries >= 25 then
        raise exception 'Could not generate a unique room code.';
      end if;
    end;
  end loop;

  insert into public.room_players (room_id, user_id, display_name, seat_index, is_ready)
  values (generated_room_id, auth.uid(), clean_name, 0, false);

  insert into public.room_states (room_id, version, state_json, updated_by)
  values (generated_room_id, 1, '{}'::jsonb, auth.uid());

  return query
  select generated_room_id, generated_code, 0;
end;
$$;

create or replace function public.join_room(
  p_room_code text,
  p_display_name text default 'Player'
)
returns table (
  room_id uuid,
  room_code text,
  seat_index integer,
  host_user_id uuid,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text;
  target_room public.rooms%rowtype;
  existing_row public.room_players%rowtype;
  chosen_seat integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  clean_name := left(coalesce(nullif(trim(p_display_name), ''), 'Player'), 32);

  select *
  into target_room
  from public.rooms
  where code = upper(trim(p_room_code))
  for update;

  if target_room.id is null then
    raise exception 'Room not found.';
  end if;

  select *
  into existing_row
  from public.room_players
  where room_id = target_room.id
    and user_id = auth.uid();

  if existing_row.user_id is not null then
    update public.room_players
    set display_name = clean_name
    where room_id = existing_row.room_id
      and user_id = existing_row.user_id;

    return query
    select
      target_room.id,
      target_room.code,
      existing_row.seat_index,
      target_room.host_user_id,
      target_room.status;
    return;
  end if;

  if target_room.status <> 'waiting' then
    raise exception 'Room is not accepting new players.';
  end if;

  if (
    select count(*)
    from public.room_players player_row
    where player_row.room_id = target_room.id
  ) >= target_room.max_players then
    raise exception 'Room is full.';
  end if;

  select seat_num
  into chosen_seat
  from generate_series(0, target_room.max_players - 1) as seat_num
  where not exists (
    select 1
    from public.room_players player_row
    where player_row.room_id = target_room.id
      and player_row.seat_index = seat_num
  )
  order by seat_num
  limit 1;

  if chosen_seat is null then
    raise exception 'No open seat available.';
  end if;

  insert into public.room_players (room_id, user_id, display_name, seat_index, is_ready)
  values (target_room.id, auth.uid(), clean_name, chosen_seat, false);

  return query
  select
    target_room.id,
    target_room.code,
    chosen_seat,
    target_room.host_user_id,
    target_room.status;
end;
$$;

create or replace function public.leave_room(p_room_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_room public.rooms%rowtype;
  remaining_count integer;
  next_host uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  select *
  into target_room
  from public.rooms
  where id = p_room_id
  for update;

  if target_room.id is null then
    return;
  end if;

  delete from public.room_players
  where room_id = p_room_id
    and user_id = auth.uid();

  select count(*) into remaining_count
  from public.room_players
  where room_id = p_room_id;

  if remaining_count = 0 then
    delete from public.rooms where id = p_room_id;
    return;
  end if;

  if target_room.host_user_id = auth.uid() then
    select user_id
    into next_host
    from public.room_players
    where room_id = p_room_id
    order by seat_index
    limit 1;

    update public.rooms
    set host_user_id = next_host
    where id = p_room_id;
  end if;
end;
$$;

grant usage on schema public to authenticated;

grant select, update on public.rooms to authenticated;
grant select on public.room_players to authenticated;
grant update (display_name, is_ready) on public.room_players to authenticated;
grant select, update on public.room_states to authenticated;
grant select, insert on public.room_actions to authenticated;
grant usage, select on sequence public.room_actions_id_seq to authenticated;

grant execute on function public.is_room_member(uuid) to authenticated;
grant execute on function public.create_room(text) to authenticated;
grant execute on function public.join_room(text, text) to authenticated;
grant execute on function public.leave_room(uuid) to authenticated;

alter table public.rooms enable row level security;
alter table public.room_players enable row level security;
alter table public.room_states enable row level security;
alter table public.room_actions enable row level security;

drop policy if exists "room members can read rooms" on public.rooms;
create policy "room members can read rooms"
on public.rooms
for select
to authenticated
using (public.is_room_member(id));

drop policy if exists "room host can update room" on public.rooms;
create policy "room host can update room"
on public.rooms
for update
to authenticated
using ((select auth.uid()) = host_user_id)
with check ((select auth.uid()) = host_user_id);

drop policy if exists "room members can read players" on public.room_players;
create policy "room members can read players"
on public.room_players
for select
to authenticated
using (public.is_room_member(room_id));

drop policy if exists "players can update own row" on public.room_players;
create policy "players can update own row"
on public.room_players
for update
to authenticated
using ((select auth.uid()) = user_id and public.is_room_member(room_id))
with check ((select auth.uid()) = user_id and public.is_room_member(room_id));

drop policy if exists "room members can read state" on public.room_states;
create policy "room members can read state"
on public.room_states
for select
to authenticated
using (public.is_room_member(room_id));

drop policy if exists "room members can update state" on public.room_states;
create policy "room members can update state"
on public.room_states
for update
to authenticated
using (public.is_room_member(room_id))
with check (public.is_room_member(room_id));

drop policy if exists "room members can insert state" on public.room_states;
create policy "room members can insert state"
on public.room_states
for insert
to authenticated
with check (public.is_room_member(room_id));

drop policy if exists "room members can read actions" on public.room_actions;
create policy "room members can read actions"
on public.room_actions
for select
to authenticated
using (public.is_room_member(room_id));

drop policy if exists "room members can insert own actions" on public.room_actions;
create policy "room members can insert own actions"
on public.room_actions
for insert
to authenticated
with check ((select auth.uid()) = actor_user_id and public.is_room_member(room_id));
